### ISSUE TITLE
can't create a new date property on a block with a value of today

### ISSUE THREAD

**Issue by blogbourri** [logseq/db-test#17]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

i created a property, date. i created a block, and tried to add the date property set to today, but it would no apply to the block. if i add the date property set to a different day, however, i can then edit the date back to today.

### Reproduce the Bug

1. start typing in a block
2. ctrl+p to add a property
3. add a property, "date" with date schema
4. try to select today's date (nothing happens)
6. select a different date (this works)
7. edit the value to today's date (this works)

### Expected Behavior

it should be possible to add a date property with a value of today's date to a block.
[console-export-2024-8-14_18-29-48.txt](https://github.com/user-attachments/files/16620453/console-export-2024-8-14_18-29-48.txt)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
Fixed.

**Comment by logseq-cldwalker** [comment]
Unless I'm misunderstanding the bug, this doesn't seem fixed as of [fff3fb9](https://github.com/logseq/logseq/pull/9858/commits/fff3fb93c043949bcb78bf8ff544560eb010dab8) - https://www.loom.com/share/928fd59c642642449c88ebd2a0efb6da. I'm mentioning this since the fix for this issue caused some bugs with the db importer and will likely be reverted
