### ISSUE TITLE
Button for managing page properties no longer exists

### ISSUE THREAD

**Issue by Bad3r** [logseq/db-test#46]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

If my memory isn't failing me there used to be a 'configure' button that is visible when hovering over a page title inside the page.

The configure option would allow the user to easily add new page properties or manage them.

Now it seems like the only way to do that is to use the shortcut CMD+p

It used to show up either in top right of the title or similar to the `Configure tag` button:
![image](https://github.com/user-attachments/assets/d559cd52-1200-438b-9ef9-e8030f625666)

**Comment by logseq-cldwalker** [comment]
Hi. We recently unified page and block editing so that setting tags and properties on a page is the same ux as a block. This is mentioned in [the nodes section](https://github.com/logseq/docs/blob/feat/db/db-version.md#nodes). I've added a [bullet point about page properties in the changes doc](https://github.com/logseq/docs/blob/feat/db/db-version-changes.md#db-graph-changes) to answer this for future users:

> Page properties are no longer set by using the first block of a page. Rather, a page property is [set the same way a block property is](https://github.com/logseq/docs/blob/feat/db/db-version.md#add-and-edit-property-values) - by editing from the page title (block content).
